### ISSUE TITLE
csound~ causing instant crashes in max

### ISSUE THREAD

**Issue by TheoLowstein** [csound/csound_tilde#13]
Hi,

I'm having a problem using the new version of csound~ 1.13.vb in Max 8.1.5. Whenever I instantiate both csound~ object and modalys~ object in the same Max session, it instantly crashes. Does anybody know why this is happening? To be clear: both of them work just fine on their own, but it crashes instantly together. I also sent a message to the Modalys Forum at the IRCAM website, but I've had no answeres as of right now. However, I strongly believe that this problem has been caused by this new version of the csound~ object, since this was not a problem before and modalys~ has not been updated in ages.

Any help is welcomed,
T.

**Comment by vlazzarini** [comment]
Just to let you know that it might take a while for this to be answered, as there is no one maintaining this project at the moment (well actually for many years now). @rorywalsh kindly did these builds, but there is no developer looking after this code.

**Comment by rorywalsh** [comment]
I will run off a new build which links against the latest Csound binaries. I'm not sure it will help, but it's all I can really do. Btw, what OS are you on?

**Comment by TheoLowstein** [comment]
Thanks for taking a look, that will be great. I'm on a Mac OS X 10.14.6.

**Comment by vlazzarini** [comment]
What Csound version do you have installed?

**Comment by TheoLowstein** [comment]
the csound version is 6.11

**Comment by vlazzarini** [comment]
Would you mind updating it to the latest release? That's fairly old. If you wait a day or two, we're just about to release 6.15.

**Comment by TheoLowstein** [comment]
I updated and the problem does seems to be solved! Thank you very much @vlazzarini !!
