### ISSUE TITLE
not working under max 8

### ISSUE THREAD

**Issue by vichug** [csound/csound_tilde#4]
Hey, 
i got this error when trying to instantiate csound~ on max 8, osx 10.14.6 :

```
2019-09-24 05:55:31.294 Max[1159:146811] Error loading /Users/vichug/Documents/Max 8/Packages/csound~_v1.1.0_double/externals/csound~.mxo/Contents/MacOS/csound~:  dlopen(/Users/vichug/Documents/Max 8/Packages/csound~_v1.1.0_double/externals/csound~.mxo/Co
 ntents/MacOS/csound~, 262): no suitable image found.  Did find:
 	/Users/vichug/Documents/Max 8/Packages/csound~_v1.1.0_double/externals/csound~.mxo/Contents/MacOS/csound~: mach-o, but wrong architecture
 	/Users/vichug/Documents/Max 8/Packages/csound~_v1.1.0_double/externals/csound~.mxo/Contents/MacOS/csound~: mach-o, but wrong architecture
```

It seems related to 64 bit vs 32 bit issue. I'm not sure what has changed since last time i have used it (i'm nto sure if it was max 6 or 7), but the behaviour regarding 32 bits and 64 bits compatibility isn't the same in max 8 iirc.
Having very limited experience in compiling for Max, i'm not sure i can help, unfortunately...

**Comment by vlazzarini** [comment]
This code is currently orphaned. If anyone wants to have a go at maintaining, they're welcome.

**Comment by vichug** [comment]
Actually, the external *does* work, at least the version from the 6.07 release : https://github.com/csound/csound/releases/tag/6.07.0 ; external here https://github.com/csound/csound/releases/download/6.07.0/Csound_tilde.6.07-OSX.zip - and apparently the external on Windows works too if you change the typo hyphen for a tilde as @merlinusambrosius stated here : https://github.com/csound/csound_tilde/issues/1#issuecomment-368686830 . 
I can't find what solved the issue, i must have mixed an older version with this one. Sorry for the noise.
So even if it's sad that this code is orphaned (since csound 6.07), at least it works for now !

**Comment by merlinusambrosius** [comment]
Try it using Ableton.
